### ISSUE TITLE
Support for other Looking Glass devices

### ISSUE THREAD

**Issue by ichlubna** [SolerSoft/Refract#10] opened 2024-06-06 11:52 UTC
Hey,
cool software! Is this only limited to the Portrait? I tried with another older model and I see a weird image with a diagonal cut in the middle.

**Comment by ichlubna** [comment] 2024-06-06 12:08
Sorry, possible duplicate of #6

**Comment by jbienz** [comment] 2024-06-26 15:42
Yeah, this would be a dupe of #6. Commented there.

**Closed as completed by jbienz** 2024-06-26 15:42 UTC
